use valueOf() to get the reference the object.
It seems as though new versions of V8 (as of node v0.7.7) will return an
Object version of a primitive when it is referenced using "this", something
silly like this would fail:

  var called = false
  called.should.equal.false

  AssertionError: expected {} to be false